sudo: false

language: node_js

node_js:
  - "0.12.7"
  - "stable"

before_install: if [[ `npm -v` != 3* ]]; then npm i -g npm@3.10.10; fi

script:
  - npm test

matrix:
  allow_failures:
    - node_js: "stable"